// <auto-generated />
using System;
using CognomeNomeMusicManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CognomeNomeMusicManager.Migrations
{
    [DbContext(typeof(MusicContext))]
    partial class MusicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Cantante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtichettaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeReale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EtichettaId");

                    b.ToTable("Cantante");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Esibizione", b =>
                {
                    b.Property<int>("FestivalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdineUscita")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VotiGiuria")
                        .HasColumnType("INTEGER");

                    b.HasKey("FestivalId", "CantanteId");

                    b.HasIndex("CantanteId");

                    b.ToTable("Esibizione");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Etichetta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SedeLegale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Etichetta");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Festival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Festival");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Cantante", b =>
                {
                    b.HasOne("CognomeNomeMusicManager.Model.Etichetta", "Etichetta")
                        .WithMany("Cantanti")
                        .HasForeignKey("EtichettaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etichetta");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Esibizione", b =>
                {
                    b.HasOne("CognomeNomeMusicManager.Model.Cantante", "Cantante")
                        .WithMany("Esibizioni")
                        .HasForeignKey("CantanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CognomeNomeMusicManager.Model.Festival", "Festival")
                        .WithMany("Esibizioni")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cantante");

                    b.Navigation("Festival");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Cantante", b =>
                {
                    b.Navigation("Esibizioni");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Etichetta", b =>
                {
                    b.Navigation("Cantanti");
                });

            modelBuilder.Entity("CognomeNomeMusicManager.Model.Festival", b =>
                {
                    b.Navigation("Esibizioni");
                });
#pragma warning restore 612, 618
        }
    }
}
